import os

# A list of the standard asset base names generated by Visual Studio
# You can add or remove names here if your assets are different.
asset_base_names = [
    "LargeTile",
    "SmallTile",
    "MediumTile",
    "Wide310x150Logo",
    "Square44x44Logo",
    "Square150x150Logo",
    "StoreLogo",
    "SplashScreen"
]

def rename_files_for_light_theme():
    """
    Finds asset files in the current directory and renames them
    to include the '.theme-light' qualifier.
    Example: 'Square44x44Logo.scale-200.png' -> 'Square44x44Logo.theme-light.scale-200.png'
    """
    files_in_directory = os.listdir('.')
    renamed_count = 0

    print("Starting file renaming process...")

    for filename in files_in_directory:
        # Check if the file is one of our assets but doesn't already have the theme name
        if any(base_name in filename for base_name in asset_base_names) and ".theme-light" not in filename:
            
            # Split the filename into its name and extension
            name_part, extension = os.path.splitext(filename)
            
            # Create the new name by inserting '.theme-light'
            new_filename = f"{name_part}.theme-light{extension}"
            
            try:
                os.rename(filename, new_filename)
                print(f"Renamed: {filename}  ->  {new_filename}")
                renamed_count += 1
            except OSError as e:
                print(f"Error renaming {filename}: {e}")

    print(f"\nProcess complete. Renamed {renamed_count} files.")

if __name__ == "__main__":
    rename_files_for_light_theme()